### ISSUE TITLE
step9 SQLに触れてみる

### ISSUE THREAD

**Issue by smptmhr** [smptmhr/el-training#21]

**Comment by smptmhr** [comment]
`rails console`上でタスクを作成
入力
```
task = Task.create(name: "create in console", start_date:"2022-05-25",
 necessary_days: 5, progress: 1, priority: 2)
```
結果
```
  TRANSACTION (0.2ms)  BEGIN
  Task Create (0.6ms)  INSERT INTO "tasks" ("name", "description", "start_date", "necessary_days", 
"progress", "priority", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING
 "id"  [["name", "create in console"], ["description", nil], ["start_date", "2022-05-25"], 
["necessary_days", 5], ["progress", 1], ["priority", 2], ["created_at", "2022-05-26 02:38:02.616400"], 
["updated_at", "2022-05-26 02:38:02.616400"]]                                               
  TRANSACTION (5.0ms)  COMMIT                                                    
=>                                                                               
#<Task:0x0000000111ed98a8     
```

indexページ上でもタスクが作成されていることを確認

**Comment by smptmhr** [comment]
## UPDATE
`rails console` 上でタスクを更新
入力
```
task.update(name: "updated in console")
```

結果
```
  TRANSACTION (0.2ms)  BEGIN
  Task Update (5.7ms)  UPDATE "tasks" SET "name" = $1, "updated_at" = $2 WHERE "tasks"."id" = $3  
[["name", "updated in console"], ["updated_at", "2022-05-26 02:50:38.750979"], ["id", 45]]                                                       
  TRANSACTION (0.6ms)  COMMIT                                                    
=> true
```

![スクリーンショット 2022-05-26 11 53 10](https://user-images.githubusercontent.com/84895022/170406007-f84f7a60-114f-4c5c-b51d-d612deeb56a4.png)

**Comment by smptmhr** [comment]
## レコードの取得

 ### 全件取得
```
Task.all
=> SELECT `tasks`.* FROM `tasks`
```

### 主キーでレコードを検索(単数)
```
Task.find(1)
=> SELECT "tasks".* FROM "tasks" WHERE "tasks"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]] 
```

### 主キーでレコードを検索(複数)
```
Task.find([1,2,3])
SELECT "tasks".* FROM "tasks" WHERE "tasks"."id" IN ($1, $2, $3)  [["id", 1], ["id", 2], ["id", 3]]  
```

**Comment by smptmhr** [comment]
## レコード削除
`rails console` 上でタスクを削除

```
task.delete
 =>DELETE FROM "tasks" WHERE "tasks"."id" = $1  [["id", 68]]
```
![スクリーンショット 2022-05-29 14 06 21](https://user-images.githubusercontent.com/84895022/170853158-b6062314-fa8a-4655-a969-c0164fd84c3e.png)


## 文法

DELETE : 対象のレコードを削除する

## 疑問点
レコード削除後に`task.valid?`をすると問題なくレコードと`true`が返ってくるのが謎。
indexページではタスクが削除されている。

**Comment by smptmhr** [comment]
# SQLインジェクション

### SQLインジェクションとは
アプリにSQLとして意味のある文字列を送り、データベースに不正にアクセスする攻撃。サーバー側では正常なSQLとして実行されてしまう。

## SQLインジェクションの例
例えば
```
Project.where("name = '#{params[:name]}'")
```
というコードに対して`' OR 1 -- `という文字列を送ると以下のSQLが実行される。
```
SELECT * FROM projects WHERE name = '' OR 1 --'
```
このSQLによってprojectsテーブルから全てのレコードが取り出されてしまう。

## RailsでのSQLインジェクション対策
>Ruby on Railsには、特殊なSQL文字をフィルタするしくみが組み込まれており、「'」「"」「NULL」「改行」をエスケープします。Model.find(id)やModel.find_by_*(引数)といったクエリでは自動的にこの対策が適用されます。ただし、SQLフラグメント、特に条件フラグメント（where("...")）、connection.execute()またはModel.find_by_sql()メソッドについては手動でエスケープする必要があります。

[Rails セキュリティガイド - Railsガイド](https://railsguides.jp/security.html#sql%E3%82%A4%E3%83%B3%E3%82%B8%E3%82%A7%E3%82%AF%E3%82%B7%E3%83%A7%E3%83%B3)

条件オプションに文字列を直接渡すのではなく、引数のように渡すことで無害化できる。
```
Model.where("zip_code = ? AND quantity >= ?", entered_zip_code, entered_quantity).first
```

**Comment by KessaPassa** [comment]
口頭でsqlインジェクションの説明もらったのでOK
