### ISSUE TITLE
step5 : データベースの設定

### ISSUE THREAD

**Issue by smptmhr** [smptmhr/el-training#4]
使用するデータベースをpostgresqlに変更する(デフォルトがsqlite3だった)

参考 : [PostgreSQLのインストールからRailsでのDB変更まで](https://qiita.com/krtsato/items/4565051608a63f11b316)

## 疑問点
- sqliteとpostgresqlは何が違う？
- DBはrailsとは別の場所で動いてて、アプリがそれを参照している？

**Comment by KessaPassa** [comment]
> sqliteとpostgresqlは何が違う？
DBはrailsとは別の場所で動いてて、アプリがそれを参照している？

口頭連携済み
が、自分の言っていることも間違いがあるかもしれないので自分でそれぞれ調べてこのissueに書き出して欲しい

**Comment by smptmhr** [comment]
## sqlite
「組み込み形式」  
クライアント側にサーバ情報を持たせる  
(アプリ内にDBが存在するイメージ)

## PostgrgeSQL
「クライアントサーバ型」
RDBMSとしての処理はサーバで行う  
同じデータベースをクライアント間で共有可能  

今回のタスク管理アプリでは、異なるクライアントから同じアカウントにログインしたときに同じ内容が表示されてほしい  
→「クライアントサーバ型」のPostgreSQLが向いている

**Comment by smptmhr** [comment]
## DBとrails  
DBはRailsとは独立して存在していて、Railsから発行されるリクエストによって参照や操作が行われる。

![スクリーンショット 2022-04-27 0 07 44](https://user-images.githubusercontent.com/84895022/165332267-0a3c8a70-1537-4124-85a0-4e185387ab07.png)

参考 :[ Rails Tutorial 2.2.2 MVCの挙動](https://railstutorial.jp/chapters/toy_app?version=5.1#sec-mvc_in_action)
