### ISSUE TITLE
step7 : タスクモデルを作成

### ISSUE THREAD

**Issue by smptmhr** [smptmhr/el-training#8]
## 概要
タスクを管理するためのCRUDを作成

## やること
- マイグレーション作成
- データベースに接続できることを確認
- バリデーション設定

## やらないこと
- ラベルとの中間テーブルの作成(step24で実行)
- タスクグループへの拡張(別イシューに切り出し)

**Comment by smptmhr** [comment]
## 困っているところ
タスクモデルの取り掛かり予定日に非NULLの制約を持たせたいが、うまくいかない。
start_date変数をDate型で用意したのがミスだった？

test/models/task_test.rb
```
  test 'parameters validation' do
    assert_not @task.valid?

    @task.task_name = 'example task'
    @task.abstract_text = 'abstract text'
    # @start_date = Date.parse('2022-05-03')
    @task.status = 0
    assert @task.valid?
  end
```

app/models/task.rb
```
class Task < ApplicationRecord
  validates :task_name,     presence: true
  validates :abstract_text, presence: true
  # validates :start_date,    presence: true
  validates :status,        presence: true
end
```

**Comment by KessaPassa** [comment]
> タスクモデルの取り掛かり予定日に非NULLの制約を持たせたいが、うまくいかない。

ふむ、`t.datetime 'created_at', null: false` と同じように `t.date 'deadline_date'` にもつけて上げたらマイグレーション通ったけれどそういうことではなく？

**Comment by KessaPassa** [comment]
なるほど。これは `@start_date = Date.parse('2022-05-03')` が原因だね
意図したいことをやるのであれば `@task.task_name = 'example task'` みたいに `@task.task_name=` ってしないといけない
start_dateだけは `@task` に紐づいていないので、なにをしても `@task.start_date` の中身が nilになってバリデーションエラーだよ！とおこられちゃってます！
